streaming_software/RadioBOSS.md
Following up on your latest [tweet](https://twitter.com/AzuraCast/status/1137787935028338689)
=> Adding RadioBOSS to the mix

StreamingSoftware.md
Seems like I didn't notice this file :)
=> Adding RadioBOSS to the index

docs/install/README.md
Updating the instruction on how to update AzuraCast's docker… 
This is to skip of having to answer the question, "Update docker-compose.yml file? This will overwrite any customizations you made to this file? [y/N]" - As we always type "y".
=> Update README.md 

docs/developers/cli.md, docs/developers/docker_sh.md
More broken links found and fixed.
=> Fixing more broken links

docs/help/streaming_software.md
Since the PORT document has been updated.
Streaming Software instructions has been updated also.
=> Updating instructions for BUTT and RadioBoss

docs/help/faq_docker.md
I've moved the `Customizing Docker` entry to the top of that page as it is the general description of the dos and don'ts when customizing docker installations so it should be the first thing to read.
We have many users who are not native english speakers so I changed `recycle` to `restart` as the meaning of it is clearer.
This PR also adds the faq entry mentioned in #16
=> Improve order of entries, clarify restarting, add entry about custom error.mp3

docs/help/streaming_software.md
Added the PlayIt Live software, along with instructions for IceCast and SHOUTcast
=> Added PlayIt Live

docs/help/faq_docker.md
=> Add FAQ entries for mounting directories into Docker

docs/help/faq_docker.md
=> Teeny Typo

docs/help/README.md
And added some extra warnings not to call via cell phones.
=> Added a discord link to 'Contact us'

docs/install/docker.md
I noticed on the main AzuraCast repository some issues that could be related to OS and if running in a non fresh install could cause some issues.
The recommendation would be to run in a fresh installed host.
I just did a fresh install on a CentOS 7 box without any issues.
=> Add a better explanation about the choice of OS.

docs/help/docker/README.md, docs/station-management/media/sftp.md
This commit updates out of date information relating to the old FTP system and updates it to be more in line with the stable version. 
I also included some FTP clients that I've tested on AzuraCast and indeed work.
=> Update SFTP documentation to be more accurate. 

docs/help/ansible/README.md, docs/install/README.md, docs/install/ansible.md
In this pull I've amended the Ansible documentation to specifically state no support is offered, due to it being unsupported.
=> Ansible documentation re-write

src/content/docs/docs/administration/cloudflare.md
CloudFlare should be "Cloudflare". Sincerly, a Cloudflare employee ;p
Just changes casing of Cloudflare.
=> CloudFlare -> Cloudflare

src/content/docs/docs/administration/advanced-features.md, src/content/docs/docs/administration/command-line-interface.md, src/content/docs/docs/administration/customization.md, src/content/docs/docs/administration/docker.md, src/content/docs/docs/getting-started/requirements.md, src/content/docs/docs/getting-started/updates/release-channels.md, src/content/docs/docs/help/logs.md, src/content/docs/docs/user-guide/mount-points.md, src/content/docs/docs/user-guide/promoting-your-station.md, src/content/docs/docs/user-guide/streaming-software.md
* Multiple broken links within administration/command-line-interface.md
* Updated links
=> Fixes broken links, expand sections

src/content/docs/docs/user-guide/station-management.md
None
Add a graph (mermaid) that displays essential components and make it easier for users to understand the stream flow and how the software works (user perspective).
=> Mermaid graph to display essential components

src/content/docs/docs/user-guide/playlists.md
NA
- update docs for advanced playlist configuration. Current docs indicate you can edit liquidsoap.liq in station settings, but it's under Broadcasting in sidebar.
=> Update location for editing liquidsoap.liq

src/content/docs/docs/developers/liquidsoap.md
* Include information on how to scrobble using Liquidsoap.
Special thanks to @gAlleb for bringing this to my attention.
=> Add Last.fm scrobbling instructions to Liquidsoap documentation

src/content/docs/docs/developers/liquidsoap.md
- Update documentation to reflect [new scrobbling code/logic](https://github.com/AzuraCast/AzuraCast/pull/7647)
=> Include info about new scrobbling config

src/content/docs/docs/getting-started/settings.md
Added explanation about NGINX_BLOCK_BOTS variable. Ref: https://github.com/AzuraCast/AzuraCast/blob/main/CHANGELOG.md#new-featureschanges-1
=> 📝 docs: added NGINX_BLOCK_BOTS variable

src/content/docs/docs/user-guide/streaming-software.md
- Resolves #109 
- Rocket Broadcaster initial docs
=> Update streaming software documentation: add Rocket Broadcaster section and improve formatting
